### ISSUE TITLE
error import fairlearn.moments

### ISSUE THREAD

**Issue by msqiqi10** [AnayMehrotra/Fair-classification-with-adversarial-perturbations#1] opened 2021-12-16 05:32 UTC
Thanks for your contribution!

I was trying to run this code but in classred.py line 22, it throws `ModuleNotFoundError: No module named 'fairlearn.moments'` when trying to `import fairlearn.moments as moments`.

Is there a way to fix this? Or is there a certain version of fairlearn I need to use?

Thanks!

**Comment by AnayMehrotra** [comment] 2021-12-16 06:35
@msqiqi10 I believe the issue is that you are trying to execute the code from inside the `fairlearn` folder, because of this Python does not recognize the module `fairlearn.moments`. The Jupyter notebooks in the project do not face this issue because they execute the code from outside the `fairlearn` folder. 

I see two fixes:

1. Replace `import fairlearn.moments as moments` by `import moments as moments` in `classred.py`. This suffices to run `classred.py`, but can lead to inconsistencies with the rest of the code.

2. The other option is to make a copy of `classred.py` outside the `fairlearn` folder (and inside `lamy_noise_fairlearn`) and run using the new copy.

**Comment by AnayMehrotra** [comment] 2021-12-22 18:34
Dear @msqiqi10, I am closing this issue for now. Please let me know if the above suggestion did not resolve the error.

**Closed as completed by AnayMehrotra** 2021-12-22 18:34 UTC
